'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Toast from '@/components/Toast';

interface GlobalRecipe {
  id: number;
  name: string;
  cuisine: string;
  mealType: string;
  total_time: string;
  prep_time: string;
  cook_time: string;
  difficulty: string;
  description: string;
  photo_url: string;
  ingredients: { amount: string; item: string }[];
  instructions: string[];
  prep_ahead: string[];
  tags: string[];
  serves: number;
}

const DIFF_STYLE: Record<string, React.CSSProperties> = {
  Easy:   { background: 'var(--green-lt)', color: 'var(--green)' },
  Medium: { background: '#FEF6E4',         color: '#7A5B10' },
  Hard:   { background: '#FDEDEB',         color: '#C0392B' },
};

export default function AdminRecipesPage() {
  const [recipes, setRecipes] = useState<GlobalRecipe[]>([]);
  const [loading, setLoading] = useState(true);
  const [toast, setToast] = useState<{ msg: string; type: 'success' | 'error' } | null>(null);
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<GlobalRecipe | null>(null);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [addingToWeek, setAddingToWeek] = useState(false);
  const [addedToWeek, setAddedToWeek] = useState(false);
  const [savedToMyRecipes, setSavedToMyRecipes] = useState(false);
  const [savingToMyRecipes, setSavingToMyRecipes] = useState(false);
  const [backfilling, setBackfilling] = useState(false);
  const [cleaning, setCleaning] = useState(false);
  const [restoring, setRestoring] = useState(false);

  const runRestore = async () => {
    if (!confirm('Scan every user\'s menus and rebuild the global library from the meal recipes embedded there. Safe (dedupes by name). Proceed?')) return;
    setRestoring(true);
    try {
      const res = await fetch('/api/admin/restore-global-from-menus', { method: 'POST' });
      const d = await res.json();
      if (!res.ok) {
        setToast({ msg: d.error || `HTTP ${res.status}`, type: 'error' });
      } else {
        const sample = d.sample?.length ? `  e.g. ${d.sample.join(', ')}` : '';
        setToast({ msg: `Restored ${d.inserted} recipes from ${d.scanned} menus.${sample}`, type: 'success' });
        fetch('/api/admin/recipes').then(r => r.json()).then(d => setRecipes(d || []));
      }
    } catch (e: any) {
      setToast({ msg: e.message || 'Network error', type: 'error' });
    } finally {
      setRestoring(false);
    }
  };

  const runCleanup = async (mode: 'standard' | 'orphans' = 'standard') => {
    const msg = mode === 'orphans'
      ? 'Aggressive cleanup: delete every dinner recipe whose name does NOT appear in any user\'s menu meals. Catches backfill leftovers with empty source, but may also remove recipes orphaned by menu deletion. Proceed?'
      : 'Delete every global recipe NOT generated by Fornello (imports, manual entries with a source field)? This cannot be undone.';
    if (!confirm(msg)) return;
    setCleaning(true);
    try {
      const url = mode === 'orphans'
        ? '/api/admin/cleanup-global-recipes?mode=orphans'
        : '/api/admin/cleanup-global-recipes';
      const res = await fetch(url, { method: 'POST' });
      const d = await res.json();
      if (!res.ok) {
        setToast({ msg: d.error || `HTTP ${res.status}`, type: 'error' });
      } else {
        const sample = d.sample?.length ? `  e.g. ${d.sample.join(', ')}` : '';
        setToast({ msg: `Deleted ${d.deleted} non-Fornello recipes.${sample}`, type: 'success' });
        fetch('/api/admin/recipes').then(r => r.json()).then(d => setRecipes(d || []));
      }
    } catch (e: any) {
      setToast({ msg: e.message || 'Network error', type: 'error' });
    } finally {
      setCleaning(false);
    }
  };

  const runBackfill = async () => {
    if (!confirm('Copy every existing user_recipes row into the global library? Idempotent — safe to re-run.')) return;
    setBackfilling(true);
    try {
      const res = await fetch('/api/admin/backfill-global-recipes', { method: 'POST' });
      const d = await res.json();
      if (!res.ok) {
        setToast({ msg: d.error || `HTTP ${res.status}`, type: 'error' });
      } else {
        const firstFail = d.failures?.[0];
        const summary = `${d.copied} copied, ${d.alreadyPresent} already there, ${d.failed} failed (of ${d.total}).`;
        const msg = d.failed > 0 && firstFail
          ? `${summary}  First failure: ${firstFail}`
          : summary;
        setToast({ msg, type: d.failed > 0 ? 'error' : 'success' });
        // Refresh the list
        fetch('/api/admin/recipes').then(r => r.json()).then(d => setRecipes(d || []));
      }
    } catch (e: any) {
      setToast({ msg: e.message || 'Network error', type: 'error' });
    } finally {
      setBackfilling(false);
    }
  };

  useEffect(() => {
    fetch('/api/admin/recipes')
      .then(r => {
        if (r.status === 403) { window.location.href = '/'; return null; }
        return r.json();
      })
      .then(d => { if (d) setRecipes(d); })
      .finally(() => setLoading(false));
  }, []);

  const openRecipe = async (id: number) => {
    setLoadingDetail(true);
    setAddedToWeek(false);
    setSavedToMyRecipes(false);
    try {
      const res = await fetch(`/api/admin/recipes/${id}`);
      const data = await res.json();
      setSelected(data);
    } finally {
      setLoadingDetail(false);
    }
  };

  const closeDetail = () => { setSelected(null); setAddedToWeek(false); };

  const saveToMyRecipes = async () => {
    if (!selected) return;
    setSavingToMyRecipes(true);
    try {
      await fetch('/api/recipes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: selected.name, cuisine: selected.cuisine, mealType: selected.mealType,
          serves: selected.serves, total_time: selected.total_time,
          prep_time: selected.prep_time, cook_time: selected.cook_time,
          difficulty: selected.difficulty, description: selected.description,
          tags: selected.tags, ingredients: selected.ingredients,
          instructions: selected.instructions, prep_ahead: selected.prep_ahead,
          photo_url: selected.photo_url || '', source: '',
        }),
      });
      setSavedToMyRecipes(true);
    } catch {
      // silently fail — user can retry
    } finally {
      setSavingToMyRecipes(false);
    }
  };

  const addToNextWeek = async () => {
    if (!selected) return;
    setAddingToWeek(true);
    try {
      await fetch('/api/menu/next-week-pick', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mealName: selected.name }),
      });
      setAddedToWeek(true);
      setToast({ msg: `"${selected.name}" queued for next week's menu ✓`, type: 'success' });
    } catch {
      setToast({ msg: 'Could not add to next week', type: 'error' });
    } finally {
      setAddingToWeek(false);
    }
  };

  const handleDelete = async (id: number, name: string) => {
    if (!confirm(`Delete "${name}" from the global library?`)) return;
    await fetch(`/api/admin/recipes/${id}`, { method: 'DELETE' });
    setRecipes(prev => prev.filter(r => r.id !== id));
    if (selected?.id === id) closeDetail();
    setToast({ msg: `"${name}" removed`, type: 'success' });
  };

  const filtered = recipes.filter(r =>
    r.name.toLowerCase().includes(search.toLowerCase()) ||
    r.cuisine.toLowerCase().includes(search.toLowerCase()) ||
    r.mealType.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="max-w-5xl mx-auto px-6 py-10">
      {toast && <Toast message={toast.msg} type={toast.type} onDone={() => setToast(null)} />}

      {/* Read-only recipe detail modal */}
      {(selected || loadingDetail) && (
        <div className="fixed inset-0 z-50 flex items-start justify-center md:p-6 overflow-y-auto"
             style={{ background: 'rgba(0,0,0,0.55)' }}
             onClick={e => e.target === e.currentTarget && closeDetail()}>
          <div className="w-full max-w-2xl md:rounded-[22px] overflow-hidden relative md:mt-4 md:mb-8"
               style={{ background: 'var(--white)', boxShadow: '0 16px 48px rgba(0,0,0,0.22)', minHeight: '60vh' }}>

            {loadingDetail ? (
              <div className="flex items-center justify-center py-32">
                <div className="spinner w-8 h-8" />
              </div>
            ) : selected ? (
              <>
                {/* Hero */}
                {selected.photo_url ? (
                  <div className="relative w-full h-52 overflow-hidden">
                    <img src={selected.photo_url} alt={selected.name} className="w-full h-full object-cover" />
                    <div className="absolute inset-0" style={{ background: 'linear-gradient(to top, rgba(30,35,30,0.7) 0%, transparent 60%)' }} />
                    <div className="absolute bottom-0 left-0 right-0 px-6 pb-5">
                      <h2 className="text-[26px] leading-tight text-white" style={{ fontFamily: 'var(--font-lora), serif' }}>
                        {selected.name}
                      </h2>
                    </div>
                    <button onClick={closeDetail}
                      className="absolute top-4 right-4 w-9 h-9 rounded-full flex items-center justify-center backdrop-blur-sm"
                      style={{ background: 'rgba(255,255,255,0.25)', color: '#fff', border: '1px solid rgba(255,255,255,0.3)' }}>
                      ✕
                    </button>
                  </div>
                ) : (
                  <div className="flex items-center justify-between px-6 pt-6 pb-2">
                    <h2 className="text-2xl" style={{ fontFamily: 'var(--font-lora), serif' }}>{selected.name}</h2>
                    <button onClick={closeDetail} className="text-xl" style={{ color: 'var(--text-3)' }}>✕</button>
                  </div>
                )}

                <div className="p-6">
                  {/* Meta */}
                  <div className="flex flex-wrap gap-4 rounded-xl p-4 mb-5" style={{ background: 'var(--cream)' }}>
                    {[
                      ['⏱ Total', selected.total_time],
                      ['🔪 Prep', selected.prep_time],
                      ['🔥 Cook', selected.cook_time],
                      ['🍴 Serves', String(selected.serves)],
                      ['🌍 Cuisine', selected.cuisine],
                    ].filter(([, v]) => v).map(([label, val]) => (
                      <div key={label} className="flex flex-col">
                        <span className="text-xs uppercase tracking-wide" style={{ color: 'var(--text-3)' }}>{label}</span>
                        <strong className="text-sm">{val}</strong>
                      </div>
                    ))}
                    {selected.difficulty && (
                      <div className="flex flex-col">
                        <span className="text-xs uppercase tracking-wide" style={{ color: 'var(--text-3)' }}>📊 Level</span>
                        <span className="text-xs font-bold px-3 py-1 rounded-full mt-0.5"
                              style={DIFF_STYLE[selected.difficulty] || DIFF_STYLE.Easy}>
                          {selected.difficulty}
                        </span>
                      </div>
                    )}
                  </div>

                  {selected.description && (
                    <p className="text-sm mb-5 italic" style={{ color: 'var(--text-2)' }}>{selected.description}</p>
                  )}

                  {/* Ingredients + Instructions */}
                  <div className="grid md:grid-cols-2 gap-8 mb-6">
                    <div>
                      <h3 className="font-bold text-lg mb-3" style={{ fontFamily: 'var(--font-lora), serif' }}>Ingredients</h3>
                      <ul className="space-y-2">
                        {(selected.ingredients || []).map((ing, i) => (
                          <li key={i} className="flex gap-3 py-2 text-sm border-b" style={{ borderColor: 'var(--cream)' }}>
                            <span className="font-semibold min-w-20 shrink-0" style={{ color: 'var(--green)' }}>{ing.amount}</span>
                            <span>{ing.item}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <h3 className="font-bold text-lg mb-3" style={{ fontFamily: 'var(--font-lora), serif' }}>Instructions</h3>
                      <ol className="space-y-3">
                        {(selected.instructions || []).map((step, i) => (
                          <li key={i} className="flex gap-2 text-sm leading-relaxed">
                            <span className="font-bold shrink-0" style={{ color: 'var(--green)', minWidth: '20px' }}>{i + 1}.</span>
                            <span>{step}</span>
                          </li>
                        ))}
                      </ol>
                    </div>
                  </div>

                  {/* Prep ahead */}
                  {selected.prep_ahead?.length > 0 && (
                    <div className="mb-6">
                      <h3 className="font-bold text-base mb-3" style={{ fontFamily: 'var(--font-lora), serif' }}>Prep Ahead</h3>
                      <ul className="space-y-2">
                        {selected.prep_ahead.map((tip, i) => (
                          <li key={i} className="flex gap-3 rounded-xl p-3 text-sm" style={{ background: 'var(--green-lt)' }}>
                            <span className="font-bold shrink-0" style={{ color: 'var(--green)' }}>✓</span>
                            <span>{tip}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Actions */}
                  <div className="flex gap-3 flex-wrap pt-2 border-t" style={{ borderColor: 'var(--border)' }}>
                    <button
                      onClick={addToNextWeek}
                      disabled={addingToWeek || addedToWeek}
                      className="px-5 py-2.5 rounded-full text-sm font-semibold transition-opacity hover:opacity-80 disabled:opacity-60"
                      style={{ background: addedToWeek ? 'var(--green-lt)' : 'var(--green)', color: addedToWeek ? 'var(--green)' : '#fff' }}>
                      {addedToWeek ? '✓ Queued for next week' : addingToWeek ? 'Adding…' : '＋ Add to next week'}
                    </button>
                    <button
                      onClick={saveToMyRecipes}
                      disabled={savingToMyRecipes || savedToMyRecipes}
                      className="px-5 py-2.5 rounded-full text-sm font-semibold transition-opacity hover:opacity-80 disabled:opacity-60"
                      style={{ background: savedToMyRecipes ? 'var(--green-lt)' : 'var(--cream)', color: savedToMyRecipes ? 'var(--green)' : 'var(--text-2)', border: '1px solid var(--border)' }}>
                      {savedToMyRecipes ? '✓ Saved to My Recipes' : savingToMyRecipes ? 'Saving…' : '📖 Save to My Recipes'}
                    </button>
                    <Link href={`/admin/recipes/${selected.id}`}
                      className="px-5 py-2.5 rounded-full text-sm font-semibold transition-opacity hover:opacity-80"
                      style={{ background: 'var(--cream)', color: 'var(--text-2)', border: '1px solid var(--border)' }}>
                      ✏ Edit recipe
                    </Link>
                    <button
                      onClick={() => handleDelete(selected.id, selected.name)}
                      className="px-5 py-2.5 rounded-full text-sm font-semibold transition-opacity hover:opacity-80 ml-auto"
                      style={{ background: '#FDEDEB', color: '#C0392B' }}>
                      Remove
                    </button>
                  </div>
                </div>
              </>
            ) : null}
          </div>
        </div>
      )}

      <div className="flex items-center justify-between gap-4 mb-8 flex-wrap">
        <div>
          <h1 className="text-3xl font-bold" style={{ fontFamily: 'AbramoSerif, serif', color: 'var(--text)' }}>
            Global Recipe Library
          </h1>
          <p className="mt-1 text-sm italic" style={{ color: 'var(--text-2)' }}>
            {recipes.length} recipe{recipes.length !== 1 ? 's' : ''} · visible to all users
          </p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button onClick={runRestore} disabled={restoring}
            className="rounded-full px-5 py-2.5 text-sm font-medium transition-opacity hover:opacity-80 disabled:opacity-50"
            style={{ border: '1px solid var(--green)', color: 'var(--green)', background: 'var(--green-lt)' }}>
            {restoring ? '⏳ Restoring…' : '↻ Restore library from menus'}
          </button>
          <Link href="/admin/recipes/new"
            className="rounded-full px-5 py-2.5 text-sm font-semibold transition-opacity hover:opacity-80"
            style={{ background: 'var(--green)', color: '#fff' }}>
            + Add Recipe
          </Link>
        </div>
      </div>

      <input
        value={search}
        onChange={e => setSearch(e.target.value)}
        placeholder="Search by name, cuisine, or type…"
        className="w-full px-4 py-3 rounded-xl border text-sm outline-none mb-6"
        style={{ background: 'var(--cream)', borderColor: 'var(--border)', fontFamily: 'Georgia, serif' }}
      />

      {loading ? (
        <div className="text-center py-20" style={{ color: 'var(--text-2)' }}>Loading…</div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-20">
          <p className="text-lg mb-2" style={{ color: 'var(--text-2)' }}>
            {search ? 'No recipes match your search.' : 'No global recipes yet.'}
          </p>
          {!search && (
            <p className="text-sm italic" style={{ color: 'var(--text-3)' }}>
              Add recipes here or promote them from a meal card in This Week.
            </p>
          )}
        </div>
      ) : (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {filtered.map(recipe => (
            <div key={recipe.id}
                 className="rounded-[18px] overflow-hidden ring-1 cursor-pointer transition-transform hover:scale-[1.01]"
                 style={{ background: 'var(--white)', boxShadow: '0 4px 16px rgba(47,58,50,0.07)' }}
                 onClick={() => openRecipe(recipe.id)}>
              {recipe.photo_url ? (
                <img src={recipe.photo_url} alt={recipe.name}
                     className="w-full h-36 object-cover"
                     style={{ filter: 'saturate(0.85) sepia(0.12)' }} />
              ) : (
                <div className="w-full h-36 flex items-center justify-center text-4xl"
                     style={{ background: 'var(--cream)' }}>🍽</div>
              )}
              <div className="p-4">
                <p className="font-semibold text-base leading-tight mb-1" style={{ color: 'var(--text)', fontFamily: 'AbramoSerif, serif' }}>
                  {recipe.name}
                </p>
                <p className="text-xs mb-1" style={{ color: 'var(--text-3)' }}>
                  {[recipe.cuisine, recipe.mealType, recipe.total_time, recipe.difficulty].filter(Boolean).join(' · ')}
                </p>
                {recipe.description && (
                  <p className="text-xs italic mb-3 line-clamp-2" style={{ color: 'var(--text-2)' }}>
                    {recipe.description}
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
