'use client';

/**
 * The full statement, shown once where allergies are entered.
 *
 * Deliberately long and unhedged. Everywhere else in the app a one-line
 * reminder is enough; this is the place someone sits down and thinks about a
 * family member's allergy, and it is the only place worth explaining WHY the
 * checks cannot be sufficient — a hidden allergen in a stock, brand variation,
 * a shared factory. Those are the failure modes an ingredient-name match will
 * never catch, and someone protecting a child deserves to know them.
 */
export default function AllergySafetyNotice() {
  return (
    <div className="rounded-xl px-5 py-4 mb-5 text-sm leading-relaxed"
         style={{ background: '#FDEDEB', border: '1px solid #E8B4AC', color: 'var(--text-2)' }}>
      <p className="mb-3" style={{ color: '#8B2E22' }}>
        <strong>Allergies and restrictions — please read this</strong>
      </p>
      <p className="mb-3">
        Tell Fornello what your household can&apos;t eat and those ingredients are kept out
        of your menus. Every recipe is checked against this list before it reaches you.
      </p>
      <p className="mb-3" style={{ color: '#8B2E22' }}>
        <strong>It is not a substitute for reading the recipe yourself.</strong>
      </p>
      <p className="mb-3">
        Fornello&apos;s recipes are generated by AI, and they can be wrong. Even a correct
        recipe can&apos;t know everything: an allergen can hide inside a stock, a sauce, a
        spice blend or a condiment without ever being named; the same product varies from
        brand to brand; and no recipe can tell you what else was made in the factory where
        an ingredient was packed.
      </p>
      <p className="mb-3">
        Fornello also only knows what you type here. Anything missing from this list
        won&apos;t be avoided.
      </p>
      <p className="mb-3">
        So before you cook, read every ingredient, and check the label on anything you
        didn&apos;t make yourself. You know your household. Fornello doesn&apos;t.
      </p>
      <p>
        If someone in your family has a severe allergy, treat every recipe as a starting
        point to check rather than a list to trust — exactly as you would a recipe from a
        cookbook or a website.
      </p>
    </div>
  );
}
