-- Record what a future stop will need, before it is needed.
--
-- The forcing function for eventually stopping is NOT AI spend — it is
-- deliverability. Gmail and Outlook score senders on engagement, so a growing
-- tail of accounts that never open, never click and never reply drags the
-- domain's reputation down, and the harm lands on the households who DO want
-- their Sunday menu, whose email starts going to spam. Dead accounts poison the
-- channel for the live ones, and money does not fix that.
--
-- Irrelevant at 16 households. Very relevant at a few thousand. So: log the
-- signal now so the decision can be made on evidence later, rather than
-- reconstructed from nothing.
--
-- Additive & safe to re-run.

ALTER TABLE settings
  -- How many times we have asked "still want your week on Sundays?".
  ADD COLUMN IF NOT EXISTS auto_plan_asks_sent int NOT NULL DEFAULT 0,
  -- Last engagement of ANY kind: menu opened, meal rated, list opened in the
  -- shop, an ask answered. Household-level so the question "has this person
  -- shown any sign of life in a year?" is one column read.
  ADD COLUMN IF NOT EXISTS last_engaged_at timestamptz;

CREATE INDEX IF NOT EXISTS settings_last_engaged_idx ON settings (last_engaged_at);

-- Existing households have all engaged — every menu on record was generated by
-- someone who was present.
UPDATE settings s
   SET last_engaged_at = COALESCE(
     s.last_engaged_at,
     (SELECT max(m.engaged_at) FROM menus m WHERE m.user_id = s.user_id)
   )
 WHERE s.last_engaged_at IS NULL;
