-- Fornello plans the week and emails it, without being visited.
--
-- Additive & safe to re-run.

-- Opt-in. Deliberately NOT defaulted true: this spends the household's AI
-- allowance without them present, so it has to be asked for.
ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS auto_plan boolean NOT NULL DEFAULT false,
  -- Consecutive auto-planned weeks with no sign of life. Resets on any
  -- engagement; at the threshold we ask once, then stop.
  ADD COLUMN IF NOT EXISTS auto_plan_ignored int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auto_plan_paused boolean NOT NULL DEFAULT false;

-- Evidence a week was actually met by a human: menu opened in the app, a meal
-- rated, a grocery item ticked, a link clicked in the email.
--
-- This exists because of the 12-week no-repeat rule. That rule excludes
-- anything "served recently" — and once Fornello generates weeks on its own,
-- unopened menus would ban their dishes for three months on the strength of
-- meals nobody ate. The engine would quietly start avoiding its best food.
-- Only engaged weeks may suppress a repeat.
ALTER TABLE menus
  ADD COLUMN IF NOT EXISTS engaged_at timestamptz,
  -- Distinguishes a week Fornello planned unasked from one the household made.
  ADD COLUMN IF NOT EXISTS auto_planned boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS menus_engaged_idx ON menus (user_id, engaged_at);

-- Existing menus predate auto-planning: every one was generated by a person who
-- was present, so all count as engaged.
UPDATE menus SET engaged_at = COALESCE(engaged_at, created_at) WHERE engaged_at IS NULL;
